name: Workflow with input
on:
  push:
    inputs:
      name:
        description: "Person to greet"
        required: true
        default: "Im in push"
      home:
        description: "location"
        required: false
      anotherVariable:
        description: "Test spacing from push"
        required: false
  workflow_dispatch:
    inputs:
      name:
        description: "Person to greet"
        required: true
        default: "Mona the Octocat"
      home:
        description: "location"
        required: false
      anotherVariable:
        description: "Test spacing"
        required: false

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run:
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.home }}!"
          echo " - using the site ${{github.event.inputs.site}}"
          # env:
          # TEST_VAR: A var from the build
