name: Triggering a worflow from another one
on:
  workflow_dispatch:
jobs:
  invoke:
    runs-on: ubuntu-latest
    name: Invoke workflow with inputs
    steps:
      - uses: actions/checkout@v2
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Workflow with input
          token: ${{ secrets.GITHUB_TOKEN  }}
          inputs: '{ "name": "Name from another workflow", "home": "London" }'
