name: Triggering a worflow from another one
on:
  push:
jobs:
  invoke:
    runs-on: ubuntu-latest
    name: Invoke workflow with inputs
    steps:
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Workflow with input
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN  }}
          inputs: '{ "name": "Name from another workflow on push", "home": "London" }'
